### PR TITLE
Use precedent in coord 3d

### PR DESCRIPTION
**Pull request by adrianq**

### CODE REVIEW

**Comment by delarosatrevin** [comment]
Precendent sounds quite strange for me. Why this naming instead of 'volume'? Has the rationale/decision discussed somewhere?

**Comment by adrianq** [comment]
Yes, it was discussed a month ago with @cossorzano @fede-pe @EstrellaFG This change is already part of the tomo branch (see https://github.com/scipion-em/scipion-em-tomo/pull/29) The reason is that we can have a set of volumes or a tilt series.

**Comment by delarosatrevin** [comment]
It would be good that these discussions (or a summary) be documented somewhere (issues, PR notes, shared doc) for other developers not in Madrid to be up to date with changes in the data model and core functionality.

**Comment by pconesa** [comment]
@adrianq what is the status of this?

**Pull request closed without merging**
