### PR TITLE
centralize napari binary installation and config var

### PR DESCRIPTION
**Pull request by azazellochg**
As discussed earlier, the binary installation is now here

### CODE REVIEW

**Comment by pconesa** [comment]
Should we bring a basic napari viewer here?

**Comment by azazellochg** [comment]
I dont know what is basic napari viewer. Coordinates viewers are specific to cryolo only or tomotwin only, they have different file formats (cbox vs tloc)

**Comment by pconesa** [comment]
So, there is no "standard" 3dcoordinate format in napari?

**Comment by azazellochg** [comment]
Unfortunately, napari devs prefer to write 100500 plugins for every file
format, for every picker etc instead of a combined effort

**Comment by azazellochg** [comment]
I can move the cbox viewer here from cryolo which will create cbox files
from any set of 3d coordinates to display.

**Comment by azazellochg** [comment]
This can be merged, I will do the viewer in the next PR

**Review by fonsecareyna82 — APPROVED** [review]

**Pull request merged**
